### ISSUE TITLE
conversion from 'xyz' (perceptual) to 'rgb' (sRGB) doesn't seem to work

### ISSUE THREAD

**Issue by dylanbeaudette** [thomasp85/farver#26]
Any ideas?
```r
# this is the expected output: 0.66387 0.50352 0.38253
convertColor(rbind(c(0.1828, 0.1844, 0.3806)), from = 'XYZ', to = 'sRGB', from.ref.white = 'D65', to.ref.white = 'D65')

# this is not
convert_colour(rbind(c(0.1828, 0.1844, 0.3806)), from = 'xyz', to = 'rgb', white_from = 'D65', white_to = 'D65')
```

**Comment by thomasp85** [comment]
farver is using the native domain of the different colourspaces whereas convertColor normalises it between 0 and 1

```r
convert_colour(rbind(c(0.1828, 0.1844, 0.3806)) * 100, from = 'xyz', to = 'rgb', white_from = 'D65', white_to = 'D65') / 255
```

will give the same result

It is not all colourspaces that have any defined bounds, so it is not possible to rescale them between 0 and 1. This is why farver leaves the colours alone

**Comment by dylanbeaudette** [comment]
Thanks. Worth a mention in the manual page? I don't see any such documentation for `grDevices::convertColor`.
