### ISSUE TITLE
CC seems hardcoded to 'gcc' ?

### ISSUE THREAD

**Issue by CdeMills** [thomasp85/farver#28]
Hello,
I'm using clang under CentOS-8 linux to compile R packages. To this end, I created  ~/R/Makevars with:
CC=clang
CXX=clang++
While performing install.packages('tidyverse'), your package was the only one compiled with gcc. Is there a reason ? If not, is gcc hardcoded as compiler ?
TIA
Pascal Dupuis

**Comment by thomasp85** [comment]
No, farver does not specify any compiler to use. Don't know why you'd get that
