### ISSUE TITLE
farver::decode_colour() could accept 3 character hex codes

### ISSUE THREAD

**Issue by francisbarton** [thomasp85/farver#41]
3 character codes like `#9aa` are a useful shorthand, and are valid in HTML/CSS.
Can farver be edited so as to accept these (and presumably convert them to the full 6 character code?)

```r
farver::decode_colour("#9aa")
✘ Error: Malformed colour string `#9aa`. Must contain either 6 or 8 hex values
```

**Comment by teunbrand** [comment]
In R-devel, the short form is now accepted. See https://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2023/09/01#n2023-09-01
